export const typographyRules = {
  h1: {
    fontFamily: 'MTSWideMedium',
    fontSize: '36px',
    fontWeight: 500,
    lineHeight: '40px',
  },
  h2: {
    fontFamily: 'MTSWideMedium',
    fontSize: '32px',
    fontWeight: 500,
    lineHeight: '36px',
  },
  h2_Comp: {
    fontFamily: 'MTSCompactMedium',
    fontSize: '32px',
    fontWeight: 500,
    lineHeight: '36px',
  },
  h3: {
    fontFamily: 'MTSWideMedium',
    fontSize: '24px',
    fontWeight: 500,
    lineHeight: '28px',
  },
  h3_Comp: {
    fontFamily: 'MTSCompactMedium',
    fontSize: '24px',
    fontWeight: 500,
    lineHeight: '28px',
  },
  h4: {
    fontFamily: 'MTSWideMedium',
    fontSize: '20px',
    fontWeight: 500,
    lineHeight: '24px',
  },
  h4_Comp: {
    fontFamily: 'MTSCompactMedium',
    fontSize: '20px',
    fontWeight: 500,
    lineHeight: '24px',
  },
  p2_Regular_Comp: {
    fontFamily: 'MTSCompactRegular',
    fontSize: '20px',
    fontWeight: 400,
    lineHeight: '28px',
  },
  p2_Regular_Text: {
    fontFamily: 'MTSTextRegular',
    fontSize: '20px',
    fontWeight: 400,
    lineHeight: '28px',
  },
  p3_Comp: {
    fontFamily: 'MTSCompactRegular',
    fontSize: '17px',
    fontWeight: 400,
    lineHeight: '24px',
  },
  p3_Medium: {
    fontFamily: 'MTSCompactMedium',
    fontSize: '17px',
    fontWeight: 500,
    lineHeight: '24px',
  },
  p3_Regular_Text: {
    fontFamily: 'MTSCompactRegular',
    fontSize: '17px',
    fontWeight: 400,
    lineHeight: '24px',
  },
  p4_Medium: {
    fontFamily: 'MTSCompactMedium',
    fontSize: '14px',
    fontWeight: 500,
    lineHeight: '20px',
  },
  p4_Regular_Comp: {
    fontFamily: 'MTSCompactRegular',
    fontSize: '14px',
    fontWeight: 400,
    lineHeight: '20px',
  },
  p4_bold_upp_wide: {
    fontFamily: 'MTSWideBlack',
    fontWeight: 700,
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: '0.05em',
  },
  p4_med_upp_wide: {
    fontFamily: 'MTSTextRegular',
    fontWeight: 500,
    fontSize: '14px',
    lineHeight: '20px',
  },
  c1_Regular_Comp: {
    fontFamily: 'MTSCompactRegular',
    fontSize: '12px',
    fontWeight: 400,
    lineHeight: '16px',
    letterSpacing: '0.4px',
  },
  c1_Medium: {
    fontFamily: 'MTSWideMedium',
    fontSize: '12px',
    fontWeight: 500,
    lineHeight: '16px',
    letterSpacing: '5%',
  },
  c1_Bold: {
    fontFamily: 'MTSWideMedium',
    fontSize: '12px',
    fontWeight: 700,
    lineHeight: '16px',
    letterSpacing: '1px',
  },
  c2_Bold: {
    fontFamily: 'MTSWideMedium',
    fontSize: '10px',
    fontWeight: 700,
    lineHeight: '12px',
    letterSpacing: '1px',
  },
  Promo2: {
    fontSize: '44px',
    fontFamily: 'MTSWideMedium',
    fontWeight: 500,
    lineHeight: '44px',
  },
}
